# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'all_track.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_all_track(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1223, 644)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("F.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 90, 1151, 531))
        self.label.setStyleSheet("#label{\n"
"    background-color:rgb(255, 255, 237)\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(510, 20, 331, 61))
        self.label_2.setStyleSheet("#label_2{\n"
"    color:rgb(48, 68, 255);\n"
"    font: 16pt \"Bernard MT Condensed\";\n"
"}")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Overview of typhoon track"))
        self.label_2.setText(_translate("Dialog", "所有台风路径总览"))
