# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Beautiful_Photo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1567, 1129)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\Pycharm\Lab\台风预报系统\F.ico"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.webEngineView.setGeometry(QtCore.QRect(10, 170, 1181, 811))
        self.webEngineView.setStyleSheet("#webEngineView{\n"
"    background-color:rgb(197, 255, 216);\n"
"}")
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1400, 80, 161, 91))
        self.pushButton.setStyleSheet("#pushButton{\n"
"    font: 87 22pt \"Arial Black\" Bold;\n"
"    font-size:36px;\n"
"    color:rgb(170, 85, 0);\n"
"    background-color:rgb(205, 255, 245)\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 90, 701, 71))
        self.label.setStyleSheet("#label{\n"
"    color:rgb(76, 28, 85);\n"
"    font: 63 27pt \"Cascadia Mono SemiBold\";\n"
"}")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(-10, -10, 1581, 91))
        self.lineEdit.setStyleSheet("#lineEdit{\n"
"    font: 87 22pt \"Arial Black\" Bold;\n"
"    font-size:36px;\n"
"    color:rgb(170, 85, 0);\n"
"    background-color:rgb(247, 255, 189)\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1190, 170, 371, 71))
        self.label_2.setStyleSheet("#label_2{\n"
"    font: 87 22pt \"Arial Black\" Bold;\n"
"    font-size:20px;\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgb(152, 142, 255)\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1190, 580, 371, 71))
        self.label_4.setStyleSheet("#label_4{\n"
"    font: 87 22pt \"Arial Black\" Bold;\n"
"    font-size:20px;\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgb(152, 142, 255)\n"
"}")
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1190, 650, 371, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1190, 720, 371, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1190, 790, 371, 71))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1190, 240, 371, 341))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1190, 930, 371, 71))
        self.label_5.setStyleSheet("#label_5{\n"
"    font: 87 22pt \"Arial Black\" Bold;\n"
"    font-size:20px;\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgb(152, 142, 255)\n"
"}")
        self.label_5.setObjectName("label_5")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(1440, 10, 91, 51))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1190, 1000, 371, 71))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1190, 860, 371, 71))
        self.pushButton_6.setObjectName("pushButton_6")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(1050, 80, 351, 91))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(18)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(700, 80, 351, 91))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(18)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 980, 1181, 91))
        self.pushButton_7.setStyleSheet("#pushButton_7{\n"
"        font: 87 22pt \"Arial Black\" Bold;\n"
"    font-size:36px;\n"
"    color:rgb(179, 111, 105);\n"
"    background-color:rgb(225, 237, 255)\n"
"\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1567, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "台风路径查询助手"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.label.setText(_translate("MainWindow", "台风路径与强度可视化查询"))
        self.lineEdit.setText(_translate("MainWindow", "                                   欢迎选择CMA数据源"))
        self.label_2.setText(_translate("MainWindow", "            台风强度预览"))
        self.label_4.setText(_translate("MainWindow", "            我国台风之最"))
        self.pushButton_2.setText(_translate("MainWindow", "路径最长"))
        self.pushButton_3.setText(_translate("MainWindow", "强度最强"))
        self.pushButton_4.setText(_translate("MainWindow", "共存最多"))
        self.label_5.setText(_translate("MainWindow", "             所有台风预览"))
        self.commandLinkButton.setText(_translate("MainWindow", "返回"))
        self.pushButton_5.setText(_translate("MainWindow", "地图可视化"))
        self.pushButton_6.setText(_translate("MainWindow", "生成最早/最晚"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "请选择台风"))
        self.comboBox.setItemText(0, _translate("MainWindow", "请选择年份"))
        self.comboBox.setItemText(1, _translate("MainWindow", "1979"))
        self.comboBox.setItemText(2, _translate("MainWindow", "1980"))
        self.comboBox.setItemText(3, _translate("MainWindow", "1981"))
        self.comboBox.setItemText(4, _translate("MainWindow", "1982"))
        self.comboBox.setItemText(5, _translate("MainWindow", "1983"))
        self.pushButton_7.setText(_translate("MainWindow", " "))
from PyQt5 import QtWebEngineWidgets
