# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face_sorce.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1561, 1106)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\Pycharm\Lab\台风预报系统\F.ico"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1150, 80, 421, 201))
        self.pushButton.setStyleSheet("#pushButton{\n"
"    font: 87 22pt \"Arial Black\" Bold;\n"
"    font-size:46px;\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgb(122, 154, 109)\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(-10, -10, 1581, 91))
        self.lineEdit.setStyleSheet("#lineEdit{\n"
"    font: 87 22pt \"Arial Black\" Bold;\n"
"    font-size:36px;\n"
"    color:rgb(170, 85, 127);\n"
"    background-color:rgb(244, 255, 238)\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(640, 80, 511, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black 12")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("#comboBox\n"
"{\n"
"    font: 87 22pt \"Arial Black\" Bold;\n"
"    font-size:36px;\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgb(181, 201, 255)\n"
"}\n"
"\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(640, 180, 511, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black 12")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("#comboBox_3{\n"
"    font: 87 22pt \"Arial Black\" Bold;\n"
"    font-size:36px;\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgb(181, 201, 255)\n"
"}\n"
"")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(1450, 10, 91, 52))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 80, 641, 201))
        self.label.setStyleSheet("#label\n"
"{\n"
"    font: 87 22pt \"Arial Black\" Bold;\n"
"    font-size:36px;\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgb(255, 116, 130)\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.webEngineView.setGeometry(QtCore.QRect(0, 280, 1561, 761))
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 280, 1561, 761))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1561, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "台风路径查询助手"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.lineEdit.setText(_translate("MainWindow", "                                 欢迎选择IBTrACS数据源"))
        self.comboBox.setItemText(0, _translate("MainWindow", "请选择年份"))
        self.comboBox.setItemText(1, _translate("MainWindow", "1979"))
        self.comboBox.setItemText(2, _translate("MainWindow", "1980"))
        self.comboBox.setItemText(3, _translate("MainWindow", "1981"))
        self.comboBox.setItemText(4, _translate("MainWindow", "1982"))
        self.comboBox.setItemText(5, _translate("MainWindow", "1983"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "请选择台风"))
        self.commandLinkButton_2.setText(_translate("MainWindow", "返回"))
        self.label.setText(_translate("MainWindow", "         全球台风总览与查询"))
from PyQt5 import QtWebEngineWidgets
