# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'function_option.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Function_Option_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1186, 784)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("F.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 280, 421, 261))
        self.pushButton.setStyleSheet("#pushButton{\n"
"    color:rgb(170, 85, 0);background:rgb(255, 254, 239);border:2px solid #F3F3F5;border-radius:45px;\n"
"                font-size:20pt; font-weight:400;font-family: Roman times;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(700, 280, 431, 261))
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"    color:rgb(170, 85, 0);background:rgb(255, 254, 239);border:2px solid #F3F3F5;border-radius:45px;\n"
"                font-size:20pt; font-weight:400;font-family: Roman times;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(280, 110, 631, 81))
        self.lineEdit.setStyleSheet("#lineEdit{\n"
"    color:rgb(255, 170, 0);\n"
"    background-color:rgb(233, 255, 208);\n"
"    \n"
"    font: 22pt \"Arial Rounded MT Bold\";\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 500, 121, 41))
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"    background-color:rgb(217, 183, 255);\n"
"    font: 12pt \"MV Boli\";\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1186, 30))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "台风路径查询助手"))
        self.pushButton.setText(_translate("MainWindow", "IBTrACS\n"
"\n"
"世界气象热带气旋"))
        self.pushButton_2.setText(_translate("MainWindow", "CMA\n"
"\n"
"中国气象局热带气旋"))
        self.lineEdit.setText(_translate("MainWindow", "            请选择台风数据源"))
        self.pushButton_3.setText(_translate("MainWindow", "退出登录"))
        self.menu.setTitle(_translate("MainWindow", "功能选择"))
